# Week 3 Assignment
* Download the "Week_3_Assignment.ipynb" notebook 
* Fill in the code in the cells marked with `# YOUR ANSWER HERE:` by answering the question/task defined in the cell above it starting with `GRADED:`
* Code cells outside of `# YOUR ANSWER HERE:` will not be considered for grading. 
  * Feel free to write outside of it for debugging
* Submit the updated notebook
  * Make sure to save your changes before submitting it!

In [1]:
# PLEASE, DO NOT MODIFY THIS CELL!

# IMPORT NECESSARY LIBRARIES AND DATA
import pandas as pd
import numpy as np

# SECtION A data
nparr = np.arange(145, 217).reshape(12, 6)

# data location
data_url = 'https://raw.githubusercontent.com/plotly/datasets/master/2011_february_us_airport_traffic.csv'
a_df = pd.read_csv(data_url, header=0)
a_df.head()


iata                            airport               city state country  \
0  ORD       Chicago O'Hare International            Chicago    IL     USA   
1  ATL  William B Hartsfield-Atlanta Intl            Atlanta    GA     USA   
2  DFW    Dallas-Fort Worth International  Dallas-Fort Worth    TX     USA   
3  PHX   Phoenix Sky Harbor International            Phoenix    AZ     USA   
4  DEN                        Denver Intl             Denver    CO     USA   

         lat        long    cnt  
0  41.979595  -87.904464  25129  
1  33.640444  -84.426944  21925  
2  32.895951  -97.037200  20662  
3  33.434167 -112.008056  17290  
4  39.858408 -104.667002  13781

## GRADED SECTION A

1. Determine the shape, number of dimensions and type of elements in the numpy array `nparr`
2. Determine the standard deviation of all elements in `nparr`
3. Determine the position (not the value) of the maximum value element in `nparr`
4. Create an array of the same shape as `nparr` but filled with zeros
5. Create an array of the same shape as `nparr` but filled with ones
6. Create an array of the same shape as `nparr` but where all elements are the square root values
7. Create an array result of shape `12` by `12` resulting from multiplication of nparr with transpose(`nparr`). Hint: use `np.dot`

In [374]:
# YOUR SECTION A ANSWER HERE (please use comments to number each of your answers)


# QUES:1 - Shape, Number of Dimensions, Type of Elements in numpy array
print("# QUES: 1 - Shape, Number of Dimensions, Type of Elements in the Numpy Array 'nparr' -")
print(f"Shape of 'nparr' : {nparr.shape}")
print(f"Number of dimensions of 'nparr' : {nparr.ndim}")
print(f"Type of elements of 'nparr' : {nparr.dtype} \n\n")


# QUES:2 - Standard Deviation of elements in numpy array
print("# QUES: 2 - Standard Deviation of elements in the Numpy Array 'nparr' : ")
print(f" {np.std(nparr)} \n\n")


# QUES:3 - Position (not the value) of the maximum value element in numpy array
print(f"# QUES: 3 - Position (not the value) of the maximum value element in the Numpy Array 'nparr' : \n {np.argmax(nparr)}st index")
x,y = np.where(nparr == np.max(nparr))
print(f"Indices of the maximum element :\n {x},{y} \n\n")


# QUES:4 - Create array of the same shape as nparr but filled with ZEROs
print("# QUES: 4 - Create array of the same shape as the Numpy array 'nparr' filled with ZEROs : ")
print(f" {np.zeros_like(nparr)} \n\n")


# QUES:5 - Create array of the same shape as nparr but filled with ONEs
print("# QUES: 5 - Create array of the same shape as the Numpy array 'nparr' filled with ONEs : ")
print(f" {np.ones_like(nparr)} \n\n")


# QUES:6 - Create array of the same shape as nparr but where all elements are the square root values
print("# QUES: 6 - Create array of the same shape as the Numpy array 'nparr' where all elements are the square root value:")
print(f" {np.sqrt(nparr)} \n\n")


# QUES:7 - Create array of the 12 by 12 shape from multiplication of nparr with transpose(nparr)
print("# QUES: 7 - Create array of the 12 by 12 shape from multiplication of the Numpy array 'nparr' with transpose(nparr):")
print(f" {np.dot(nparr, np.transpose(nparr))} \n\n")

# QUES: 1 - Shape, Number of Dimensions, Type of Elements in the Numpy Array 'nparr' -
Shape of 'nparr' : (12, 6)
Number of dimensions of 'nparr' : 2
Type of elements of 'nparr' : int64 


# QUES: 2 - Standard Deviation of elements in the Numpy Array 'nparr' : 
 20.7826049057058 


# QUES: 3 - Position (not the value) of the maximum value element in the Numpy Array 'nparr' : 
 71st index
Indices of the maximum element :
 [11],[5] 


# QUES: 4 - Create array of the same shape as the Numpy array 'nparr' filled with ZEROs : 
 [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]] 


# QUES: 5 - Create array of the same shape as the Numpy array 'nparr' filled with ONEs : 
 [[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]] 


# QUES: 6 - 

## GRADED SECTION B

The dataframe `a_df` loads the dataset that contains information on a number of categories regarding traffic (variable `cnt` represents the actual traffic) at US airports from February 2011.
The dataset has already been loaded for you in the first code cell above.
 1. Print the number of rows for the subset of the dataframe for which traffic values are higher than `10,000` (ideally, you should format the print to put the thousands comma separator--as in `23,400` instead of `23400`
 2. Print the names of all the columns of the dataframe
 3. Print a subset of the dataframe containing the `10th` and the `3rd` rows of the original dataframe (`in that order`).
 4. Which US `state` has the `8th` largest __total__ airport traffic? Please, make sure you use the correct variable as described above.
 5. Which state has the second-most __total__ number of airports (i.e. the second-most amount of airports)?
 6. Of the cities that have multiple airports, which one has the least total traffic for all airports?
 7. What is the total airport traffic for all states that border the state of Massachusetts?


In [375]:
# YOUR SECTION B ANSWER HERE (please use comments to number each of your answers)

# QUES:1 - Print rows and its number where traffic values are higher than 10,000
print("# QUES: 1 - Print rows and its number where traffic values are higher than 10,000 : ")

new_df = a_df.loc[a_df['cnt'] > 10000]
new_df['cnt'] = new_df['cnt'].apply(lambda row: "{:,}".format(row))
display(new_df)
print("\n")


# QUES:2 - Print names of all columns of the dataframe
print("# QUES: 2 - Print list of names of all columns of the dataframe 'a_df' : ")
print(f" {list(a_df.columns)} \n\n")


# QUES:3 - Print subset of the dataframe containing 10th and 3rd row in same order
print("# QUES: 3 - Print subset of the dataframe 'a_df' containing 10th and 3rd row in same order : ")
display(a_df.iloc[[9,2]])
print("\n")


# QUES:4 - Print US state with 8th largest 'total' airport traffic in the dataframe
print("# QUES: 4 - Print US state with 8th largest 'total' airport traffic in the dataframe 'a_df' : ")
print(f" {a_df.sort_values(by='cnt', ascending=False).state.iloc[7]} \n\n")


# QUES:5 - Print US state with second-most total number of airports in the dataframe
print("# QUES: 5 - Print US state with second-most total number of airports in the dataframe 'a_df' : ")
print(f" {a_df['state'].value_counts().index.tolist()[1]} \n\n")


# QUES:6 - Print US city with least total traffic for all airports amongst those having multiple airports in the dataframe
print("# QUES: 6 - Print US city with least total traffic for all airports from having multiple airports in the dataframe: ")
list_cities = a_df['city'].value_counts()[a_df['city'].value_counts() > 1].index.tolist()
city_with_least_airports = a_df.loc[a_df['city'].isin(list_cities)].groupby('city').sum().sort_values(by='cnt', ascending=True)
print(f" {city_with_least_airports.iloc[0].name} \n\n")


# QUES:7 - Print total airport traffic for all states that border the state of Massachusetts
print("# QUES: 7 - Print total airport traffic for all states that border the state of Massachusetts in the dataframe : ")
print(f" {a_df.loc[a_df['state'].isin(['NH', 'VT', 'RI', 'NY', 'CT'])].sum().cnt:,} \n\n")



# QUES: 1 - Print rows and its number where traffic values are higher than 10,000 : 


iata                            airport               city state country  \
0  ORD       Chicago O'Hare International            Chicago    IL     USA   
1  ATL  William B Hartsfield-Atlanta Intl            Atlanta    GA     USA   
2  DFW    Dallas-Fort Worth International  Dallas-Fort Worth    TX     USA   
3  PHX   Phoenix Sky Harbor International            Phoenix    AZ     USA   
4  DEN                        Denver Intl             Denver    CO     USA   
5  IAH       George Bush Intercontinental            Houston    TX     USA   
6  SFO        San Francisco International      San Francisco    CA     USA   
7  LAX          Los Angeles International        Los Angeles    CA     USA   
8  MCO              Orlando International            Orlando    FL     USA   
9  CLT    Charlotte/Douglas International          Charlotte    NC     USA   

         lat        long     cnt  
0  41.979595  -87.904464  25,129  
1  33.640444  -84.426944  21,925  
2  32.895951  -97.037200  20,662  
3  33.434167 -112.008056  17,290  
4  39.858408 -104.667002  13,781  
5  29.980472  -95.339722  13,223  
6  37.619002 -122.374843  12,016  
7  33.942536 -118.408074  11,797  
8  28.428889  -81.316028  10,536  
9  35.214011  -80.943126  10,490



# QUES: 2 - Print list of names of all columns of the dataframe 'a_df' : 
 ['iata', 'airport', 'city', 'state', 'country', 'lat', 'long', 'cnt'] 


# QUES: 3 - Print subset of the dataframe 'a_df' containing 10th and 3rd row in same order : 


iata                          airport               city state country  \
9  CLT  Charlotte/Douglas International          Charlotte    NC     USA   
2  DFW  Dallas-Fort Worth International  Dallas-Fort Worth    TX     USA   

         lat       long    cnt  
9  35.214011 -80.943126  10490  
2  32.895951 -97.037200  20662



# QUES: 4 - Print US state with 8th largest 'total' airport traffic in the dataframe 'a_df' : 
 CA 


# QUES: 5 - Print US state with second-most total number of airports in the dataframe 'a_df' : 
 TX 


# QUES: 6 - Print US city with least total traffic for all airports from having multiple airports in the dataframe: 
 Charleston 


# QUES: 7 - Print total airport traffic for all states that border the state of Massachusetts in the dataframe : 
 22,007 




In [27]:
#Correction for B1
new_df = a_df.loc[a_df['cnt'] > 10000]
new_df['cnt'] = new_df['cnt'].apply(lambda row: "{:,}".format(row))
print(f" Number of records : {new_df['cnt'].count()} \n\n")

#Correction for B4
cntSortedStates = a_df.groupby('state')['cnt'].sum().sort_values(ascending=False).reset_index()
print("# QUES: 4 - Print US state with 8th largest 'total' airport traffic in the dataframe 'a_df' : ")
print(f" {cntSortedStates.state.iloc[7]} \n\n")

 Number of records : 10 


# QUES: 4 - Print US state with 8th largest 'total' airport traffic in the dataframe 'a_df' : 
 CO 




/var/folders/p0/x0tmw85n4p90cmmlj82vk6r00000gn/T/ipykernel_19807/2391740019.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['cnt'] = new_df['cnt'].apply(lambda row: "{:,}".format(row))
